[package]
name = "comic-fs"
version = "0.1.0"
authors = ["DanSnow <dododavid006@gmail.com>"]
edition = "2018"

[workspace]
members = [".", "fuse-rs", "fuse-rs/fuse-abi", "fuse-rs/fuse-sys"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.5", features = ["sqlite"] }
dotenv = "0.15.0"
fuse = { path = "fuse-rs" }
