version: '3'
services:
  web:
    build: .
    depends_on:
      - redis
    ports:
      - "5000:5000"
    volumes:
      - "./storage:/storage"
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse:/dev/fuse"
    security_opt:
      - apparmor:unconfined
  redis:
    image: redis
